# Generated by Django 4.1.7 on 2023-03-27 22:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('src', models.ImageField(blank=True, max_length=200, null=True, upload_to='image', verbose_name='首页轮播图')),
            ],
        ),
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=128, verbose_name='手机号')),
                ('weixin', models.CharField(max_length=128, verbose_name='微信')),
                ('address', models.CharField(max_length=256, verbose_name='地址')),
                ('sumery', ckeditor.fields.RichTextField(verbose_name='商店简介')),
            ],
        ),
    ]
