# Generated by Django 4.1.7 on 2023-03-28 00:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shangmen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shangpin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('src', models.ImageField(max_length=200, upload_to='image', verbose_name='头图')),
                ('view_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='对比价格')),
                ('real_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='真实价格')),
                ('tag', models.CharField(choices=[('ms', '秒杀'), ('yh', '优惠'), ('cx', '促销')], max_length=128, verbose_name='标签')),
                ('sumery', ckeditor.fields.RichTextField(verbose_name='商品介绍')),
                ('isPublish', models.IntegerField(choices=[(1, '发布'), (0, '未发布')])),
            ],
            options={
                'verbose_name_plural': '商店详情',
            },
        ),
        migrations.AlterModelOptions(
            name='homebar',
            options={'verbose_name_plural': '首页轮播图'},
        ),
        migrations.AlterModelOptions(
            name='shopinfo',
            options={'verbose_name_plural': '商店详情'},
        ),
        migrations.AlterField(
            model_name='homebar',
            name='src',
            field=models.ImageField(max_length=200, upload_to='image', verbose_name='首页轮播图'),
        ),
    ]
